"""empty message

Revision ID: 127fb510febd
Revises: 5e906d6e6664
Create Date: 2024-10-18 22:19:41.653864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127fb510febd'
down_revision = '5e906d6e6664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
