"""empty message

Revision ID: 3527c9514757
Revises: 56e8f87f1852
Create Date: 2024-10-16 23:57:34.382116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3527c9514757'
down_revision = '56e8f87f1852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.drop_column('ingredient_order')

    # ### end Alembic commands ###
