"""empty message

Revision ID: 41de854968c9
Revises: 
Create Date: 2024-11-15 22:43:22.528310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41de854968c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('calories', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('menu_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('no_raw_fish', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('mercury_sensitivity_pregnancy', sa.Boolean(), nullable=True),
    sa.Column('keto_low_carb', sa.Boolean(), nullable=True),
    sa.Column('egg_free', sa.Boolean(), nullable=True),
    sa.Column('no_seaweed', sa.Boolean(), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('gluten_intolerance', sa.Boolean(), nullable=True),
    sa.Column('carnivore', sa.Boolean(), nullable=True),
    sa.Column('lactose_intolerance', sa.Boolean(), nullable=True),
    sa.Column('soy_free', sa.Boolean(), nullable=True),
    sa.Column('low_sodium', sa.Boolean(), nullable=True),
    sa.Column('kosher', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dairy', sa.Boolean(), nullable=True),
    sa.Column('eggs', sa.Boolean(), nullable=True),
    sa.Column('seafood', sa.Boolean(), nullable=True),
    sa.Column('shellfish', sa.Boolean(), nullable=True),
    sa.Column('wheat', sa.Boolean(), nullable=True),
    sa.Column('soybeans', sa.Boolean(), nullable=True),
    sa.Column('sesame', sa.Boolean(), nullable=True),
    sa.Column('tree_nuts', sa.Boolean(), nullable=True),
    sa.Column('peanuts', sa.Boolean(), nullable=True),
    sa.Column('pork', sa.Boolean(), nullable=True),
    sa.Column('beef', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dish_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_order', sa.Integer(), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('no_raw_fish', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('mercury_sensitivity_pregnancy', sa.Boolean(), nullable=True),
    sa.Column('keto_low_carb', sa.Boolean(), nullable=True),
    sa.Column('egg_free', sa.Boolean(), nullable=True),
    sa.Column('no_seaweed', sa.Boolean(), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('gluten_intolerance', sa.Boolean(), nullable=True),
    sa.Column('carnivore', sa.Boolean(), nullable=True),
    sa.Column('lactose_intolerance', sa.Boolean(), nullable=True),
    sa.Column('soy_free', sa.Boolean(), nullable=True),
    sa.Column('low_sodium', sa.Boolean(), nullable=True),
    sa.Column('kosher', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restriction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('dairy', sa.Boolean(), nullable=True),
    sa.Column('eggs', sa.Boolean(), nullable=True),
    sa.Column('seafood', sa.Boolean(), nullable=True),
    sa.Column('shellfish', sa.Boolean(), nullable=True),
    sa.Column('wheat', sa.Boolean(), nullable=True),
    sa.Column('soybeans', sa.Boolean(), nullable=True),
    sa.Column('sesame', sa.Boolean(), nullable=True),
    sa.Column('tree_nuts', sa.Boolean(), nullable=True),
    sa.Column('peanuts', sa.Boolean(), nullable=True),
    sa.Column('pork', sa.Boolean(), nullable=True),
    sa.Column('beef', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restriction')
    op.drop_table('preference')
    op.drop_table('favorite')
    op.drop_table('dish_ingredient')
    op.drop_table('user_restrictions')
    op.drop_table('user_preferences')
    op.drop_table('menu_availability')
    op.drop_table('dish')
    op.drop_table('user')
    op.drop_table('menu')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
