"""empty message

Revision ID: 45bfc29c56e7
Revises: d979e65c518d
Create Date: 2024-09-28 00:41:22.293172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bfc29c56e7'
down_revision = 'd979e65c518d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restriction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.alter_column('menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.alter_column('dish_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('menu_availability', schema=None) as batch_op:
        batch_op.alter_column('menu_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_availability', schema=None) as batch_op:
        batch_op.alter_column('menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('dish_ingredient', schema=None) as batch_op:
        batch_op.alter_column('ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('dish_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('dish', schema=None) as batch_op:
        batch_op.alter_column('menu_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('restriction')
    # ### end Alembic commands ###
