"""empty message

Revision ID: 476b721992fb
Revises: fe56542b9554
Create Date: 2024-09-27 23:16:03.318897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476b721992fb'
down_revision = 'fe56542b9554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    # ### end Alembic commands ###
