"""empty message

Revision ID: 56e8f87f1852
Revises: 81f8bbc14eba
Create Date: 2024-10-10 00:20:57.364894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e8f87f1852'
down_revision = '81f8bbc14eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('menu_availability', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.DATE(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint('menu_availability_day_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_availability', schema=None) as batch_op:
        batch_op.create_unique_constraint('menu_availability_day_key', ['day'])
        batch_op.alter_column('day',
               existing_type=sa.String(length=120),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
