"""empty message

Revision ID: 81f8bbc14eba
Revises: 4401f06b7122
Create Date: 2024-10-10 00:05:01.529901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81f8bbc14eba'
down_revision = '4401f06b7122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('menu_availability', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Date(),
               postgresql_using="day::date", 
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_availability', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('day',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
