"""empty message

Revision ID: aff75564559c
Revises: b6211c20468e
Create Date: 2024-11-06 22:20:55.842090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff75564559c'
down_revision = 'b6211c20468e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.alter_column('calories',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               nullable=False)

    # ### end Alembic commands ###
